// Code generated by logcopter-gen; DO NOT EDIT.

package chatserver

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("hyperslop-systems.pbui.pkg.chatserver")
