---
version: "2"

linters:
  default: none
  enable:
    - errcheck
    - exhaustive
    - govet
    - ineffassign
    - nonamedreturns
    - predeclared
    - staticcheck
    - unused
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - fmt.Fprintf
        - fmt.Fprintln

formatters:
  enable:
    - gofmt
