import { describe, expect, test } from "vitest";
import { emptyDocument, sequentialIds } from "@hyperslop-systems/workbench-core";
import { leaves } from "@hyperslop-systems/workbench-protocol/client";
import type { Node } from "@hyperslop-systems/workbench-protocol";
import "../src/apps/all";
import { intersectScopes } from "../src/appkit/AppScope";
import { datalabManifests } from "../src/appkit/workbenchApps";
import { mergePinned, type RestoredLayout } from "../src/store/merge";
import { durableNavigation, type StageDefinition } from "../src/store/navigation";
import { migrate, PERSISTENCE_VERSION, validate } from "../src/store/persist";
import { createDatalabRuntime, type DatalabRuntime } from "../src/store/runtime";
import {
  compileSeed,
  defaultSeed,
  pinnedDefinitions,
  singleStageSeed,
  split,
  tile,
  type DatalabSeed,
} from "../src/store/seed";
import {
  ACCOUNT_SPACE_ID,
  ACCOUNT_STAGE_ID,
  DEMO_SPACE_IDS,
  landingStageFor,
  SIGNIN_STAGE_ID,
  stageIsVisible,
  TEMPLATES_SPACE_ID,
  WELCOME_SPACE_ID,
  WELCOME_STAGE_ID,
  WORK_STAGE_ID,
} from "../src/store/stages";
import v1Payload from "./fixtures/persisted-v1.json";
import v5Payload from "./fixtures/persisted-v5.json";

/**
 * Stages: the layer above workspaces (DATADROP-8 DR-58 … DR-61, DR-73),
 * over workbench-core (PBUI-DATALAB-WORKBENCH-1).
 *
 * Three things here are worth more than the rest and are the reason the file
 * exists:
 *
 *  - the **stage-memory invariant**, walked over every controller operation
 *    that can move the user. The old slice mirrored the current workspace in
 *    two fields and needed a test per reducer to keep them in step (DR-60);
 *    the pointer is now the core's session, and what the product adds is the
 *    memory — which must always agree with where the user actually is.
 *  - the **clean break**, against a version-1 payload produced by the
 *    version-1 source itself. The fixture in `test/fixtures/persisted-v1.json`
 *    was generated by running `defaultSpaces()` out of commit f53be15 rather
 *    than hand-written, so it is what a real browser held rather than what
 *    someone remembered it holding.
 *  - **scope composition**, including the empty intersection, which is the case
 *    that renders a blank dropdown if `Tile`'s own-application rule is ever
 *    dropped.
 */

const apps = datalabManifests();
const chrome = { masthead: true, workspaces: true, stageBar: true };

const viewIdOf = (node: Node): string => (node.body.case === "leaf" ? node.body.value.viewId : "");

/** A seed's workspaces belonging to one stage, in document order. */
const workspacesOf = (seed: DatalabSeed, stageId: string) =>
  seed.document.workspaces.filter(
    (space) => seed.navigation.workspace[space.id]?.stageId === stageId,
  );

/** A seed as a previous session would have stored it: the durable navigation, nothing more. */
const restoredFrom = (seed: DatalabSeed): RestoredLayout => ({
  document: seed.document,
  navigation: durableNavigation(seed.navigation),
  workspaceId: seed.workspaceId,
});

/* --------------------------------------------------- the pinned stages -- */

describe("the pinned stages", () => {
  test("there are four, all pinned, and the sign-in stage offers only the door", () => {
    const { stages } = pinnedDefinitions();
    expect(stages.map((s) => s.id)).toEqual([
      SIGNIN_STAGE_ID,
      WELCOME_STAGE_ID,
      ACCOUNT_STAGE_ID,
      WORK_STAGE_ID,
    ]);
    expect(stages.every((s) => s.pinned)).toBe(true);

    const signin = stages.find((s) => s.id === SIGNIN_STAGE_ID) as StageDefinition;
    // One workspace, so a strip would be a control that cannot control.
    expect(signin.chrome.workspaces).toBe(false);
    /*
     * The stage bar is SHOWN, and the change was the point of DATADROP-14.
     *
     * It used to be false, on the grounds that "a visitor who is not signed in
     * must not be offered a switcher to a stage whose every tile would show
     * 401". That was the only mechanism available for saying it, and it said it
     * by making the sign-in stage a dead end: somewhere the gate put you, with
     * no route out.
     *
     * `audience` says the same thing precisely (DR-94), so the switcher can be
     * shown without offering `work` or `account` — and a visitor who opened the
     * sign-in stage and thought better of it now has a way back to `welcome`.
     * `stage-visibility` below is what keeps the 401 promise.
     */
    expect(signin.chrome.stageBar).toBe(true);
    expect(signin.apps).toEqual(["signin", "signup", "about"]);
  });

  test("work is the only stage with no allow-list", () => {
    const withoutScope = pinnedDefinitions().stages.filter((s) => s.apps === null);
    expect(withoutScope.map((s) => s.id)).toEqual([WORK_STAGE_ID]);
  });

  test("every pinned workspace names a stage that exists", () => {
    const { stages, workspaces } = pinnedDefinitions();
    const ids = new Set(stages.map((s) => s.id));
    expect(workspaces.filter((s) => !ids.has(s.stageId))).toEqual([]);
  });

  test("the default seed lands on work, on a workspace that exists", () => {
    const seed = defaultSeed({ apps });
    const meta = seed.navigation.workspace[seed.workspaceId];
    expect(meta?.stageId).toBe(WORK_STAGE_ID);
    expect(seed.document.workspaces.find((s) => s.id === seed.workspaceId)?.name).toBe("build");
    expect(seed.navigation.rememberedWorkspaceByStage[WORK_STAGE_ID]).toBe(seed.workspaceId);
    // The work stage owns no pinned workspaces: they are a starting point the
    // user owns, renameable and deletable.
    expect(
      workspacesOf(seed, WORK_STAGE_ID).every((s) => !seed.navigation.workspace[s.id]?.pinned),
    ).toBe(true);
  });

  test("seeded singleton applications share one logical view across workspaces", () => {
    const seed = defaultSeed({ apps });
    for (const appId of ["sources", "inspector", "about"]) {
      const viewIds = seed.document.viewOrder.filter(
        (id) => seed.document.views[id]?.appId === appId,
      );
      expect(viewIds, `${appId} logical views`).toHaveLength(1);

      const placements = seed.document.workspaces.flatMap((space) =>
        leaves(space.tree).filter((placement) => viewIdOf(placement) === viewIds[0]),
      );
      expect(placements.length, `${appId} placements`).toBeGreaterThan(1);
      expect(new Set(placements.map((placement) => placement.id)).size).toBe(placements.length);
    }
  });

  test("no two seeds agree on a workspace id that is not code-defined", () => {
    // The same property `test/instances.test.ts` states for whole runtimes,
    // asserted here at the source: a fixed id on an UNPINNED workspace would
    // make two independent workbenches collide, and `work`'s opening `build`
    // workspace is the one that nearly was one.
    const a = defaultSeed({ apps });
    const b = defaultSeed({ apps });
    const bIds = new Set(b.document.workspaces.map((s) => s.id));
    const shared = a.document.workspaces.filter((s) => bIds.has(s.id));
    expect(shared.length).toBeGreaterThan(0);
    expect(shared.every((s) => a.navigation.workspace[s.id]?.pinned)).toBe(true);
  });
});

/* ------------------------------------------------- stage visibility -- */

describe("stage visibility (DATADROP-14 DR-94)", () => {
  const byId = (id: string): StageDefinition =>
    pinnedDefinitions().stages.find((s) => s.id === id) as StageDefinition;

  const visibleTo = (authed: boolean): string[] =>
    pinnedDefinitions()
      .stages.filter((stage) => stageIsVisible(stage, authed))
      .map((stage) => stage.id);

  test("a signed-out visitor sees welcome and sign in, and nothing else", () => {
    // The promise DATADROP-8 kept by making the sign-in stage a dead end, now
    // kept precisely: no route is offered to a stage whose every tile is a 401.
    expect(visibleTo(false)).toEqual([SIGNIN_STAGE_ID, WELCOME_STAGE_ID]);
  });

  test("a signed-in user sees welcome, account and work, but not sign in", () => {
    // `sign in` is EXCLUSIVE rather than a minimum: offering it to someone
    // already signed in is offering to sign them in again.
    expect(visibleTo(true)).toEqual([WELCOME_STAGE_ID, ACCOUNT_STAGE_ID, WORK_STAGE_ID]);
  });

  test("welcome is the one stage both sides share", () => {
    // The whole shape of DATADROP-14 in one assertion: a stranger and a
    // signed-in user look at the same stage, and the only difference is what
    // else they can reach from it.
    const both = visibleTo(false).filter((id) => visibleTo(true).includes(id));
    expect(both).toEqual([WELCOME_STAGE_ID]);
  });

  test("a stage that says nothing is visible to everyone", () => {
    // The default MUST be permissive: `audience` is optional so that no
    // user-created stage has to have an opinion, and a stage a user made must
    // not vanish because the field was never set.
    const mine: StageDefinition = { id: "mine", name: "mine", apps: null, chrome };
    expect(stageIsVisible(mine, true)).toBe(true);
    expect(stageIsVisible(mine, false)).toBe(true);
    expect(stageIsVisible({ ...mine, audience: "any" }, false)).toBe(true);
  });

  test("signing out lands on welcome, not on a sign-in wall", () => {
    // Both directions of the rule, and the second is the one worth stating:
    // someone who has just chosen to leave should not be met with a demand to
    // come back. `landingStageFor` is the only place that choice is made.
    expect(landingStageFor(true)).toBe(WORK_STAGE_ID);
    expect(landingStageFor(false)).toBe(WELCOME_STAGE_ID);
    expect(stageIsVisible(byId(landingStageFor(false)), false)).toBe(true);
    expect(stageIsVisible(byId(landingStageFor(true)), true)).toBe(true);
  });

  test("every landing destination is itself visible", () => {
    // Guards the loop: a landing stage the caller may not see would send the
    // gate's effect straight back round, dispatching on every render forever.
    for (const authed of [true, false]) {
      expect(stageIsVisible(byId(landingStageFor(authed)), authed)).toBe(true);
    }
  });

  test("an anonymous visitor lands on a welcome workspace that exists", () => {
    // `ws-welcome` is pinned, and a stage whose remembered workspace names a
    // workspace that is not there renders an empty shell.
    const seed = defaultSeed({ apps });
    expect(seed.navigation.rememberedWorkspaceByStage[WELCOME_STAGE_ID]).toBe(WELCOME_SPACE_ID);
    expect(seed.document.workspaces.some((s) => s.id === WELCOME_SPACE_ID)).toBe(true);
    expect(seed.navigation.workspace[WELCOME_SPACE_ID]).toEqual({
      stageId: WELCOME_STAGE_ID,
      pinned: true,
      apps: null,
    });
  });

  test("welcome presents start, four lessons, then demo pages five through seven", () => {
    const seed = defaultSeed({ apps });
    const welcome = workspacesOf(seed, WELCOME_STAGE_ID);
    expect(welcome.map((space) => space.name)).toEqual([
      "start here",
      "1·objects",
      "2·pipeline",
      "3·encode",
      "4·docs",
      "5·climate",
      "6·operations",
      "7·compare",
    ]);
    expect(welcome.slice(-3).map((space) => space.id)).toEqual([...DEMO_SPACE_IDS]);
    expect(welcome.every((space) => seed.navigation.workspace[space.id]?.pinned)).toBe(true);
  });

  test("the welcome stage offers a way to sign in and sign up from where you are", () => {
    // The highest-leverage line in DATADROP-14: a visitor who has just built a
    // chart is the most likely person in the product to want an account, and
    // making them find a different stage first is how you lose them.
    const welcome = byId(WELCOME_STAGE_ID);
    expect(welcome.apps).toContain("signin");
    expect(welcome.apps).toContain("signup");
  });

  test("audience is taken from code on merge, never from storage", () => {
    // Unlike the remembered workspace, which IS taken from storage (DR-60). A
    // payload written before this field existed — or one edited by hand —
    // must not be able to make `work` visible to an anonymous visitor.
    const stored = restoredFrom(defaultSeed({ apps }));
    stored.navigation = {
      ...stored.navigation,
      stages: stored.navigation.stages.map((stage) => ({
        ...stage,
        audience: "anonymous" as const,
      })),
    };
    const merged = mergePinned(defaultSeed({ apps }), stored, { apps })!;
    const work = merged.navigation.stages.find((s) => s.id === WORK_STAGE_ID) as StageDefinition;
    expect(work.audience).toBe("authenticated");
    expect(stageIsVisible(work, false)).toBe(false);
  });
});

/* ---------------------------------------------------- stage memory -- */

/** Two stages with two workspaces each, so every guard is live; one id generator for seed and core. */
function twoStages(): DatalabRuntime {
  const ids = sequentialIds();
  const pair = () => split("row", 0.5, tile("chart"), tile("table"));
  const seed = compileSeed({
    stages: [
      { id: "s1", name: "one", apps: null, chrome },
      { id: "s2", name: "two", apps: null, chrome },
    ],
    workspaces: [
      { id: "s1-a", name: "s1-a", stageId: "s1", spec: pair() },
      { id: "s1-b", name: "s1-b", stageId: "s1", spec: pair() },
      { id: "s2-a", name: "s2-a", stageId: "s2", spec: pair() },
      { id: "s2-b", name: "s2-b", stageId: "s2", spec: pair() },
    ],
    apps,
    ids,
    current: "s1-a",
  });
  return createDatalabRuntime({ seed, apps, ids, ownership: "trust" });
}

const session = (rt: DatalabRuntime) => rt.core.getState().session;

describe("stage memory never disagrees with where the user is", () => {
  /**
   * One representative call per controller operation that can move the
   * user or change what a stage owns. An operation added to the controller
   * without an entry here is not exercised, which is the failure mode a
   * table like this usually has — so the coverage test below names them.
   */
  const OPERATIONS: Record<string, (rt: DatalabRuntime) => void> = {
    selectWorkspace: (rt) => rt.controller.selectWorkspace("s2-b"),
    selectStage: (rt) => rt.controller.selectStage("s2"),
    createWorkspace: (rt) => rt.controller.createWorkspace({ name: "fresh" }),
    "createWorkspace in another stage": (rt) =>
      rt.controller.createWorkspace({ name: "fresh", stageId: "s2" }),
    "removeWorkspace of the current one": (rt) => rt.controller.removeWorkspace("s1-a"),
    "removeWorkspace of another stage's remembered one": (rt) => {
      rt.controller.selectWorkspace("s2-b");
      rt.controller.selectStage("s1");
      rt.controller.removeWorkspace("s2-b");
    },
    renameWorkspace: (rt) => rt.controller.renameWorkspace("s1-a", "renamed"),
    cloneWorkspace: (rt) => rt.controller.cloneWorkspace("s1-a"),
    "cloneWorkspace in another stage": (rt) => rt.controller.cloneWorkspace("s2-a"),
    "moveWorkspaceToStage of the current one": (rt) =>
      rt.controller.moveWorkspaceToStage("s1-a", "s2"),
    "moveWorkspaceToStage of another stage's": (rt) =>
      rt.controller.moveWorkspaceToStage("s2-a", "s1"),
    setWorkspaceApps: (rt) => rt.controller.setWorkspaceApps("s1-a", ["chart"]),
    addStage: (rt) => rt.controller.addStage("fresh"),
    "removeStage of the current one": (rt) => {
      rt.controller.selectStage("s2");
      rt.controller.removeStage("s2");
    },
    "removeStage of another": (rt) => rt.controller.removeStage("s2"),
    renameStage: (rt) => rt.controller.renameStage("s2", "renamed"),
  };

  test("every navigation operation on the controller is exercised here", () => {
    const rt = twoStages();
    const navigation = [
      "selectWorkspace",
      "selectStage",
      "createWorkspace",
      "removeWorkspace",
      "renameWorkspace",
      "cloneWorkspace",
      "moveWorkspaceToStage",
      "setWorkspaceApps",
      "addStage",
      "removeStage",
      "renameStage",
    ];
    for (const name of navigation)
      expect(typeof rt.controller[name as keyof typeof rt.controller]).toBe("function");
    const covered = new Set(Object.keys(OPERATIONS).map((label) => label.split(" ")[0]));
    expect(navigation.filter((name) => !covered.has(name))).toEqual([]);
  });

  test("after every operation the current stage remembers the workspace on screen", () => {
    // The failure DR-60 exists to prevent: you are on `gallery` in `work`, you
    // switch to `account` to mint a token, you switch back, and you are on
    // `build` because the memory and the pointer disagreed.
    const failures: string[] = [];
    for (const [name, operate] of Object.entries(OPERATIONS)) {
      const rt = twoStages();
      operate(rt);
      const nav = rt.store.getState().navigation;
      const current = session(rt).workspaceId;
      const stageId = rt.controller.currentStageId();
      const present = new Set(rt.core.getState().document.workspaces.map((space) => space.id));
      if (!nav.stages.some((stage) => stage.id === stageId))
        failures.push(`${name}: the current stage "${stageId}" is not defined`);
      if (nav.workspace[current]?.stageId !== stageId)
        failures.push(`${name}: the workspace on screen is filed under another stage`);
      if (nav.rememberedWorkspaceByStage[stageId] !== current)
        failures.push(
          `${name}: stage ${stageId} remembers ${nav.rememberedWorkspaceByStage[stageId]}, but ${current} is on screen`,
        );
      for (const [remembering, remembered] of Object.entries(nav.rememberedWorkspaceByStage)) {
        if (!present.has(remembered) || nav.workspace[remembered]?.stageId !== remembering)
          failures.push(`${name}: stage ${remembering} remembers a workspace it does not own`);
      }
    }
    expect(failures).toEqual([]);
  });

  test("switching stages remembers each stage's workspace, in the product's own stages", () => {
    const ids = sequentialIds();
    const rt = createDatalabRuntime({
      seed: defaultSeed({ apps, ids }),
      apps,
      ids,
      ownership: "trust",
    });
    const gallery = rt.controller
      .workspacesOfStage(WORK_STAGE_ID)
      .find((s) => s.name === "gallery")!;
    rt.controller.selectWorkspace(gallery.id);
    expect(rt.controller.selectStage(ACCOUNT_STAGE_ID).ok).toBe(true);
    expect(session(rt).workspaceId).toBe(ACCOUNT_SPACE_ID);
    rt.controller.selectStage(WORK_STAGE_ID);
    expect(session(rt).workspaceId).toBe(gallery.id);
  });

  test("switching to a workspace in another stage switches the stage too", () => {
    const ids = sequentialIds();
    const rt = createDatalabRuntime({
      seed: defaultSeed({ apps, ids }),
      apps,
      ids,
      ownership: "trust",
    });
    expect(rt.controller.currentStageId()).toBe(WORK_STAGE_ID);
    rt.controller.selectWorkspace(TEMPLATES_SPACE_ID);
    expect(rt.controller.currentStageId()).toBe(ACCOUNT_STAGE_ID);
    expect(rt.store.getState().navigation.rememberedWorkspaceByStage[ACCOUNT_STAGE_ID]).toBe(
      TEMPLATES_SPACE_ID,
    );
  });
});

/* ---------------------------------------------------------- the guards -- */

describe("deletion keeps the same guard at every level", () => {
  test("removeWorkspace counts within the STAGE, not the document", () => {
    // The old guard was "at least two workspaces", which under stages is wrong
    // in the permissive direction: a stage holding one workspace inside a
    // document holding twelve would let you delete it, leaving a stage whose
    // canvas is empty with no way back (DR-72).
    const ids = sequentialIds();
    const seed = compileSeed({
      stages: [
        { id: "s1", name: "one", apps: null, chrome },
        { id: "s2", name: "two", apps: null, chrome },
      ],
      workspaces: [
        { id: "only", name: "only", stageId: "s1", spec: tile("chart") },
        { id: "elsewhere", name: "elsewhere", stageId: "s2", spec: tile("chart") },
      ],
      apps,
      ids,
      current: "only",
    });
    const rt = createDatalabRuntime({ seed, apps, ids, ownership: "trust" });
    expect(rt.controller.removeWorkspace("only")).toMatchObject({
      ok: false,
      code: "last_workspace_in_stage",
    });
    expect(rt.core.getState().document.workspaces.map((s) => s.id)).toContain("only");
  });

  test("a pinned workspace and a pinned stage refuse removal and rename, by code", () => {
    const ids = sequentialIds();
    const rt = createDatalabRuntime({
      seed: defaultSeed({ apps, ids }),
      apps,
      ids,
      ownership: "trust",
    });
    expect(rt.controller.removeWorkspace(ACCOUNT_SPACE_ID)).toMatchObject({
      code: "pinned_workspace",
    });
    expect(rt.controller.renameWorkspace(ACCOUNT_SPACE_ID, "mine")).toMatchObject({
      code: "pinned_workspace",
    });
    expect(rt.controller.removeStage(ACCOUNT_STAGE_ID)).toMatchObject({ code: "pinned_stage" });
    expect(rt.controller.renameStage(ACCOUNT_STAGE_ID, "mine")).toMatchObject({
      code: "pinned_stage",
    });
    expect(rt.core.getState().index.workspaceById.get(ACCOUNT_SPACE_ID)?.name).toBe("profile");
    expect(rt.store.getState().navigation.stages.find((s) => s.id === ACCOUNT_STAGE_ID)?.name).toBe(
      "account",
    );
  });

  test("the last stage cannot be removed", () => {
    const ids = sequentialIds();
    const seed = singleStageSeed("build", tile("chart"), { apps, ids });
    const rt = createDatalabRuntime({ seed, apps, ids, ownership: "trust" });
    const only = rt.store.getState().navigation.stages[0]!;
    expect(rt.controller.removeStage(only.id)).toMatchObject({ ok: false, code: "last_stage" });
    expect(rt.store.getState().navigation.stages).toHaveLength(1);
  });
});

/* ------------------------------------------------------------- scopes -- */

describe("application scope composes by intersection", () => {
  test("null contributes nothing", () => {
    expect(intersectScopes(null, null)).toBeNull();
    expect(intersectScopes(null, ["chart", "table"])).toEqual(["chart", "table"]);
  });

  test("most restrictive wins", () => {
    expect(intersectScopes(["chart", "table", "trace"], ["chart", "trace"], ["trace"])).toEqual([
      "trace",
    ]);
  });

  test("an empty intersection is legal and is the empty array, never null", () => {
    // A stage offering ["signin"] inside an instance offering ["chart"]. It
    // must not be confused with "no constraint", which would offer everything —
    // the exact inversion of what the composition was asked for.
    expect(intersectScopes(["chart"], ["signin"])).toEqual([]);
  });
});

/* ------------------------------------------------------- the migration -- */

describe("canonical persistence clean break", () => {
  test("the legacy fixture is genuinely old and is rejected", () => {
    expect(v1Payload.version).toBe(1);
    expect(v1Payload.layout.spaces).toHaveLength(10);
    expect(migrate(v1Payload)).toBeNull();
    expect(validate(v1Payload, apps)).toBeNull();
  });

  test("the former version-2 analytical shape is rejected without migration", () => {
    const legacy = { ...v1Payload, version: 2 };
    expect(migrate(legacy)).toBeNull();
    expect(validate(legacy, apps)).toBeNull();
  });

  test("migrate is identity-only for the current version", () => {
    const current = { version: PERSISTENCE_VERSION };
    expect(migrate(current)).toBe(current);
    expect(migrate(migrate(current))).toBe(current);
  });

  test("a version-5 payload is transcribed into the current envelope rather than refused (DR-73)", () => {
    const migrated = migrate(v5Payload) as Record<string, unknown> | null;
    expect(migrated).not.toBeNull();
    expect(migrated?.version).toBe(PERSISTENCE_VERSION);
    expect(Object.keys(migrated!).sort()).toEqual([
      "navigation",
      "version",
      "workbench",
      "workspaceId",
      "world",
    ]);
    expect(migrated?.world).toBe(v5Payload.world);
  });
});

/* ------------------------------------------------------- mergePinned -- */

describe("mergePinned", () => {
  /** The views a seed's PINNED workspaces reach, by id. */
  const pinnedViewsOf = (seed: DatalabSeed): Set<string> =>
    new Set(
      seed.document.workspaces
        .filter((space) => seed.navigation.workspace[space.id]?.pinned)
        .flatMap((space) => leaves(space.tree).map(viewIdOf)),
    );

  test("replacing pinned workspaces does not retain their obsolete view records", () => {
    // A previous session's seed, ids and all, restored under a build whose
    // seed minted its own; every view the old pinned pages reached is stale.
    const previous = defaultSeed({ apps });
    const stale = pinnedViewsOf(previous);
    const current = defaultSeed({ apps });
    const merged = mergePinned(current, restoredFrom(previous), { apps })!;
    expect(merged).not.toBeNull();
    expect(merged.document.viewOrder.filter((id) => stale.has(id))).toEqual([]);
    expect(Object.keys(merged.document.views).filter((id) => stale.has(id))).toEqual([]);
  });

  test("a view a user workspace reaches survives; a singleton it shares with a pinned page is repointed", () => {
    const previous = defaultSeed({ apps });
    const stale = pinnedViewsOf(previous);
    const build = previous.document.workspaces.find((s) => s.id === previous.workspaceId)!;
    const own = leaves(build.tree)
      .map(viewIdOf)
      .filter((id) => !stale.has(id));
    expect(own.length).toBeGreaterThan(0);

    const current = defaultSeed({ apps });
    const merged = mergePinned(current, restoredFrom(previous), { apps })!;
    for (const id of own) expect(merged.document.views[id], `${id} survives`).toBeDefined();

    // `explore` places `sources`, which the tour pages also place: the user's
    // leaf now shows THIS build's singleton, not a second copy of it.
    const explore = merged.document.workspaces.find((s) => s.name === "explore")!;
    const sources = leaves(explore.tree)
      .map(viewIdOf)
      .filter((id) => merged.document.views[id]?.appId === "sources");
    expect(sources).toHaveLength(1);
    expect(stale.has(sources[0]!)).toBe(false);
    expect(current.document.views[sources[0]!]?.appId).toBe("sources");
    expect(
      Object.values(merged.document.views).filter((view) => view.appId === "sources"),
    ).toHaveLength(1);
  });

  test("a workspace whose stage is gone joins work rather than vanishing", () => {
    const previous = defaultSeed({ apps });
    const restored = restoredFrom(previous);
    restored.navigation = {
      ...restored.navigation,
      workspace: {
        ...restored.navigation.workspace,
        [previous.workspaceId]: { stageId: "gone", pinned: false, apps: null },
      },
    };
    const merged = mergePinned(defaultSeed({ apps }), restored, { apps })!;
    expect(merged.document.workspaces.some((s) => s.id === previous.workspaceId)).toBe(true);
    expect(merged.navigation.workspace[previous.workspaceId]?.stageId).toBe(WORK_STAGE_ID);
  });

  test("a stage with no workspaces at all gets one launcher workspace", () => {
    // Nothing stored: the pinned pages come from code, and `work`, which pins
    // nothing, would otherwise be a stage with an empty canvas.
    const nothing: RestoredLayout = {
      document: emptyDocument({ id: "datalab" }),
      navigation: { stages: [], workspace: {}, rememberedWorkspaceByStage: {} },
      workspaceId: "",
    };
    const merged = mergePinned(defaultSeed({ apps }), nothing, { apps })!;
    expect(merged).not.toBeNull();
    for (const stage of merged.navigation.stages) {
      const own = workspacesOf(merged, stage.id);
      expect(own.length, `${stage.id} has a workspace`).toBeGreaterThan(0);
      expect(own.some((s) => s.id === merged.navigation.rememberedWorkspaceByStage[stage.id])).toBe(
        true,
      );
    }
    const [work] = workspacesOf(merged, WORK_STAGE_ID);
    const tiles = leaves(work!.tree);
    expect(tiles).toHaveLength(1);
    expect(merged.document.views[viewIdOf(tiles[0]!)]?.appId).toBe("launcher");
    expect(merged.navigation.workspace[work!.id]?.pinned).toBe(false);
  });

  test("a pinned stage keeps its remembered workspace but not its definition", () => {
    const restored: RestoredLayout = {
      document: emptyDocument({ id: "datalab" }),
      navigation: {
        stages: [
          {
            id: ACCOUNT_STAGE_ID,
            name: "renamed by a user",
            apps: ["chart"],
            chrome: { masthead: false, workspaces: false, stageBar: false },
          },
        ],
        workspace: {},
        rememberedWorkspaceByStage: { [ACCOUNT_STAGE_ID]: TEMPLATES_SPACE_ID },
      },
      workspaceId: "",
    };
    const merged = mergePinned(defaultSeed({ apps }), restored, { apps })!;
    const account = merged.navigation.stages.find(
      (s) => s.id === ACCOUNT_STAGE_ID,
    ) as StageDefinition;
    expect(account.name).toBe("account");
    expect(account.apps).not.toEqual(["chart"]);
    expect(account.chrome.workspaces).toBe(true);
    expect(account.pinned).toBe(true);
    expect(merged.navigation.rememberedWorkspaceByStage[ACCOUNT_STAGE_ID]).toBe(TEMPLATES_SPACE_ID);
  });

  test("the user's own stages survive beside the pinned ones", () => {
    const previous = defaultSeed({ apps });
    const restored = restoredFrom(previous);
    restored.navigation = {
      ...restored.navigation,
      stages: [
        ...restored.navigation.stages,
        { id: "mine", name: "client demo", apps: null, chrome },
      ],
      workspace: {
        ...restored.navigation.workspace,
        [previous.workspaceId]: { stageId: "mine", pinned: false, apps: null },
      },
    };
    const merged = mergePinned(defaultSeed({ apps }), restored, { apps })!;
    expect(merged.navigation.stages.map((s) => s.id)).toEqual([
      SIGNIN_STAGE_ID,
      WELCOME_STAGE_ID,
      ACCOUNT_STAGE_ID,
      WORK_STAGE_ID,
      "mine",
    ]);
    expect(merged.navigation.workspace[previous.workspaceId]?.stageId).toBe("mine");
    expect(merged.workspaceId).toBe(previous.workspaceId);
  });
});
