// Code generated by logcopter-gen; DO NOT EDIT.

package authkit

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var log = logcopter.Package("hyperslop-systems.pbui.pkg.authkit")
