import { CUSTOMERS, type Customer } from "./customers";
import { PRODUCTS, type Product } from "./products";

/*
 * The order book: sixty-five orders over the summer of 2026, ids 88150–88214.
 *
 * Eight are ANCHORS written by hand: the four the chat demo already knows
 * (same customer, total, item count, date and status — its SKU tile quotes
 * them) and the four others that `Product.lastOrder` points at. The rest are
 * generated by a seeded linear congruential generator at module load, so
 * every run, every test and every screenshot sees the same book, and there
 * is no JSON file to keep in step with the generator.
 */

export type OrderStatus = "paid" | "shipped" | "pending" | "hold" | "cancelled";

export interface Order {
  id: string;
  customerId: string;
  /** Denormalised for the table row; equals the customer's name. */
  customer: string;
  placedAt: string;
  status: OrderStatus;
  /** Units across all line items. */
  items: number;
  total: number;
}

export interface LineItem {
  /** `${orderId}:${productId}`, unique. */
  id: string;
  orderId: string;
  productId: string;
  qty: number;
  unitPrice: number;
}

interface Anchor {
  id: string;
  customer: string;
  placedAt: string;
  status: OrderStatus;
  lines: readonly [productId: string, qty: number][];
}

const ANCHORS: readonly Anchor[] = [
  { id: "88150", customer: "Castellano Family Trust", placedAt: "2026-06-02", status: "shipped", lines: [["5001", 2]] },
  { id: "88177", customer: "K. Brennan", placedAt: "2026-07-14", status: "shipped", lines: [["2301", 1]] },
  { id: "88190", customer: "T. Nguyen", placedAt: "2026-08-05", status: "shipped", lines: [["2077", 3]] },
  { id: "88201", customer: "M. Okafor", placedAt: "2026-08-12", status: "shipped", lines: [["2051", 1]] },
  { id: "88209", customer: "Harbor Coin & Bullion", placedAt: "2026-08-14", status: "paid", lines: [["4002", 60]] },
  { id: "88210", customer: "S. Yamada", placedAt: "2026-08-15", status: "shipped", lines: [["3110", 1]] },
  { id: "88213", customer: "J. Alvarez", placedAt: "2026-08-18", status: "shipped", lines: [["2049", 3]] },
  { id: "88214", customer: "Northgate Capital", placedAt: "2026-08-19", status: "paid", lines: [["4001", 400]] },
];

const FIRST_ID = 88150;
const LAST_ID = 88214;
const FIRST_DAY = Date.UTC(2026, 5, 1); // 2026-06-01
const SPAN_DAYS = 92; // through 2026-08-31

/** Seeded LCG, the same constants the rebalance lab uses; reproducible per seed. */
function rng(seed: number): () => number {
  let state = seed >>> 0;
  return () => {
    state = (state * 1664525 + 1013904223) >>> 0;
    return state / 4294967296;
  };
}

function isoDay(offset: number): string {
  return new Date(FIRST_DAY + offset * 86_400_000).toISOString().slice(0, 10);
}

function customerByName(name: string): Customer {
  const found = CUSTOMERS.find((customer) => customer.name === name);
  if (!found) throw new Error(`pbui-ecommerce: anchor order names unknown customer "${name}"`);
  return found;
}

function productById(id: string): Product {
  const found = PRODUCTS.find((product) => product.id === id);
  if (!found) throw new Error(`pbui-ecommerce: line item names unknown product "${id}"`);
  return found;
}

/** A plausible quantity for one line, by metal: silver moves by the tube, gold by the coin. */
function quantityFor(product: Product, rand: () => number): number {
  if (product.metal === "silver") return 5 + Math.floor(rand() * 56);
  if (product.metal === "platinum") return 1 + Math.floor(rand() * 2);
  return 1 + Math.floor(rand() * 4);
}

const STATUSES: readonly OrderStatus[] = ["shipped", "shipped", "shipped", "paid", "paid", "pending", "hold", "cancelled"];

function build(): { orders: Order[]; lineItems: LineItem[] } {
  const orders: Order[] = [];
  const lineItems: LineItem[] = [];
  const rand = rng(20260901);
  const anchors = new Map(ANCHORS.map((anchor) => [anchor.id, anchor]));

  const push = (id: string, customer: Customer, placedAt: string, status: OrderStatus, lines: readonly [string, number][]) => {
    let items = 0;
    let total = 0;
    for (const [productId, qty] of lines) {
      const product = productById(productId);
      items += qty;
      total += qty * product.price;
      lineItems.push({ id: `${id}:${productId}`, orderId: id, productId, qty, unitPrice: product.price });
    }
    orders.push({ id, customerId: customer.id, customer: customer.name, placedAt, status, items, total: Math.round(total * 100) / 100 });
  };

  for (let n = FIRST_ID; n <= LAST_ID; n += 1) {
    const id = String(n);
    const anchor = anchors.get(id);
    if (anchor) {
      push(id, customerByName(anchor.customer), anchor.placedAt, anchor.status, anchor.lines);
      continue;
    }
    // Ids are roughly chronological: the day follows the id with a little jitter.
    const day = Math.min(SPAN_DAYS - 1, Math.max(0, Math.round(((n - FIRST_ID) / (LAST_ID - FIRST_ID)) * (SPAN_DAYS - 1) + (rand() * 6 - 3))));
    const customer = CUSTOMERS[Math.floor(rand() * CUSTOMERS.length)]!;
    const lineCount = 1 + Math.floor(rand() * 3);
    const chosen = new Set<string>();
    const lines: [string, number][] = [];
    while (lines.length < lineCount) {
      const product = PRODUCTS[Math.floor(rand() * PRODUCTS.length)]!;
      if (chosen.has(product.id)) continue;
      chosen.add(product.id);
      lines.push([product.id, quantityFor(product, rand)]);
    }
    const status = STATUSES[Math.floor(rand() * STATUSES.length)]!;
    push(id, customer, isoDay(day), status, lines);
  }
  return { orders, lineItems };
}

const built = build();

export const ORDERS: readonly Order[] = built.orders;
export const LINE_ITEMS: readonly LineItem[] = built.lineItems;

/** The ids of the hand-written orders, for tests that pin the chat demo's numbers. */
export const ANCHOR_ORDER_IDS: readonly string[] = ANCHORS.map((anchor) => anchor.id);
