import "./styles.css";

export { createShop, createShopWorkbench } from "./createShop";
export type { CreateShopOptions, CreateShopWorkbenchOptions, Shop } from "./createShop";
export { APP_IDS, CONTEXTS, SHOP_GROUP, createShopApps } from "./apps";
export { createShopHost, FIXTURES, IDENTITY_FIELDS, TABLES, useHostRevision } from "./host";
export type { ShopData, ShopHost, TableName, TableRows } from "./host";
export * from "./fixtures";
export * from "./presentation";
export { PLOT_FORMAT, PLOT_SCHEMA_VERSION, PLOT_SLOT, TABLE_FORMAT, TABLE_SCHEMA_VERSION, TABLE_SLOT, listPlotDocuments, plotDocumentMutation, readPlotDocument, readTableName, tableDocumentId, tableDocumentMutation } from "./document";
export { ORDERS_BY_STATUS, REVENUE_BY_CATEGORY, REVENUE_BY_DAY, SEEDED_PLOTS } from "./plots/documents";
export type { SeededPlot } from "./plots/documents";
export { SCHEMAS, plotDataFor } from "./plots/schemas";
export { SEED_DOCUMENT_ID, SEED_DOCUMENT_NAME, plotTile, seedShopDocument } from "./seed";
export type { SeedOptions } from "./seed";
export { ShopShell } from "./ShopShell";
export type { ShopShellProps } from "./ShopShell";
export { OrdersTable } from "./tiles/OrdersTable";
export { CustomersTable } from "./tiles/CustomersTable";
export { ProductCatalog } from "./tiles/ProductCatalog";
export { OrderDetail } from "./tiles/OrderDetail";
export { CustomerDetail } from "./tiles/CustomerDetail";
export { Inspector } from "./tiles/Inspector";
export { ShopPlot } from "./tiles/ShopPlot";
